### ISSUE TITLE
guidance

### ISSUE THREAD

**Issue by svshubhm** [vontell/Bility#21]
Hello sir,
I am student and a enthusiast who want to work in the  field of Accessibility.
Saw your project but didn't get much of it.
I am trying to build Accessibility scanner for android apps.
Any help will be appreciated.
Regards

**Comment by svshubhm** [comment]
Thank you! for your reply Sir.
This means a lot to me.
Looking forward for your post.

**Comment by vontell** [comment]
Just an update on this: the README has a few more instructions, a script to start all services is in the works (still a few bugs), and the thesis has been added to the root directory as `Thesis.pdf`.

Over the next week or so I will continue to improve this script and the readme.
