### ISSUE TITLE
Regarding Bility Frontend

### ISSUE THREAD

**Issue by svshubhm** [vontell/Bility#23]
Hello Sir,
I tried building "Bility" on my local Ubuntu machine,
everything went fine but I am unable to get the emulator on the bility-frontend.
Please find the attached screenshot.
 
![screenshot from 2019-02-17 20-38-38](https://user-images.githubusercontent.com/29166235/53025416-e2fcef80-3486-11e9-991e-f8da1416aaa4.png)

**Comment by vontell** [comment]
Are you able to build and run Minicap? In the start script, the Minicap server is started, connects to the device, and begins displaying. Note that your emulator has to be up and running in order to be seen. You will also need Android's NDK installed.

```
# First, download dependencies
if [ ! -d "dependencies/" ]; then
  # Control will enter here if $DIRECTORY doesn't exist.
  mkdir dependencies
fi

if [ ! -d "dependencies/minicap" ]; then
  # Control will enter here if $DIRECTORY doesn't exist.
  echo Installing Minicap... this may take a minute...
  cd dependencies
  git clone $MINICAP_REPO minicap
  cd minicap
  git submodule init
  git submodule update
  ndk-build -C . >> ../../log.txt
  cd ../../
  echo Minicap build finished!
else
  echo Minicap ready
fi

......

# Startup the emulator if not already started
echo Starting up emulator...
STARTEMCOMM="$EM -avd $EM_TO_USE -netdelay none -netspeed full -verbose -no-window"
$EM -avd $EM_TO_USE -netdelay none -netspeed full >> log.txt &
# possible -no-window

trap 'adb kill-server; echo Killed ABD server' 0

A=$(adb shell getprop sys.boot_completed | tr -d '\r')
while [ "$A" != "1" ]; do
        printf '.'
        sleep 2
        A=$(adb shell getprop sys.boot_completed | tr -d '\r')
done

echo Emulator ready!

# Start running the minicap service
echo Starting up minicap...

cd dependencies/minicap/
./run.sh -P 1080x1920@810x1440/0 >> ../../log.txt &

echo Minicap started! Forwarding feed...
adb forward tcp:1717 localabstract:minicap >> ../../log.txt

cd example/
echo Starting minicap casting server...
node app.js & >> ../../../log.txt

until $(curl --output /dev/null --silent --head --fail localhost:9002); do
    printf '.'
    sleep 1
done

echo Minicap casting server started

```

Do you get any errors when running the start script?

**Comment by svshubhm** [comment]
Yes Sir, I am to able build and run minicap server except the "fsevents" dependency which is optional  as it says.
I guess I am missing something regarding "ktor-server".
I have attached the logs this time.
![log](https://user-images.githubusercontent.com/29166235/53285941-738c4600-378d-11e9-85c7-ccee7e1c90ba.png)

please find the attachment!

**Comment by vontell** [comment]
I see, @svshubhm do you have the Android NDK installed?

**Comment by vontell** [comment]
C++ issues caused when running minicap are usually caused by a lack of Android NDK being installed (note that the NDK is separate from the Android SDK). You will also need to make sure to have your Android NDK location set as an environment variable
